"""rename Attachment field

Revision ID: 5c66673e875a
Revises: c420ec2211b6
Create Date: 2025-02-10 16:12:44.455746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c66673e875a'
down_revision: Union[str, None] = 'c420ec2211b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('image_path', sa.String(length=1000), nullable=False))
    op.drop_column('attachments', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'image_path')
    # ### end Alembic commands ###
