"""fix

Revision ID: 67fa25ffc7e5
Revises: 56f5c4e92288
Create Date: 2024-05-04 22:40:35.785486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fa25ffc7e5'
down_revision: Union[str, None] = '56f5c4e92288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_tweet_id_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_user_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'tweet', ['tweet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tweet_user_id_fkey', 'tweet', type_='foreignkey')
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.create_foreign_key('tweet_user_id_fkey', 'tweet', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_user_id_fkey', 'like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('like_tweet_id_fkey', 'like', 'tweet', ['tweet_id'], ['id'])
    # ### end Alembic commands ###
